### ISSUE TITLE
continue development

### ISSUE THREAD

**Issue by smoebody** [theimo1221/NodeMerlinWrtApi#1]
Hi, 

i recently bought me a asus-router (TUF AX3000_v2), installed the merlin-firmware and now i wanted to fetch some infos with your library. Unfortunately its rather old and not working anymore. For once there is no `asus_token` anymore, but `asus_s_token`.
I would like to fix that and develop the lib further. Maybe you can answer some questions while they pop up?

For first: you put `@types/jest` and `@types/node-fetch` into `dependencies`. Is there a reason for that? IMHO its sufficient to put these into `devDependencies`.

cheers

**Comment by theimo1221** [comment]
Hi @smoebody, 

personally my home network outgrew Asus, thus I moved over to Unifi, so feel free to do the modifications 👍 

Whilst I agree on `@types/jest` not being necessary, you should consider leaving `node-fetch` as a normal dependency, as any exports from this library containing parts of those types wouldn't be resolvable by consumers otherwise. 

Best regards

**Comment by smoebody** [comment]
Hi @theimo1221, I merged my changes, but somehow i cannot get a new release to build. The github actions always fail. Can you explain how this has to be done?

**Comment by theimo1221** [comment]
Haven't you seen the question I asked on your PR about the deactivation of certain compiler checks?

**Comment by theimo1221** [comment]
Releases are performed having an non pushed commit and then running respective npm task like `release-patch`

**Comment by smoebody** [comment]
> Haven't you seen the question I asked on your PR about the deactivation of certain compiler checks?

No, I can not see any question. Where did you ask?

**Comment by theimo1221** [comment]
![image](https://github.com/user-attachments/assets/9b3b9b07-2852-429a-bf60-1e2852ad3983)

**Comment by smoebody** [comment]
Na, nothing. Maybe because its "pending" somehow?

![image](https://github.com/user-attachments/assets/45b7ce78-6f63-4d30-87c0-f1b35b2c8517)

To answer your questions: I wanted to remove what is implicitly set already. However i misread the default `tsconfig.json` and commented out lines do not represent the default value. I will readd the checks.

`strictNullChecks` is implicitly `true` though, when `strict` is `true`.

**Comment by smoebody** [comment]
I guess  we can close this.
